Repository wecode-bootcamp-korea/17-1st-SweetHome-backend, pull requests merged in 2021-02, with the labels that each got.

#1 [17기 박재현] 모델 작성
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  posting/__init__.py
  posting/admin.py
  posting/apps.py
  posting/migrations/0001_initial.py
  posting/migrations/0002_auto_20210218_0153.py
  posting/migrations/0003_auto_20210218_0722.py
  posting/migrations/0004_auto_20210218_1052.py
  posting/migrations/__init__.py
  posting/models.py
  posting/tests.py
  posting/urls.py
  posting/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210218_0722.py
  product/migrations/0003_auto_20210218_1045.py
  product/migrations/0004_auto_20210219_0534.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/urls.py
  product/views.py
  sweethome/settings.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210219_0056.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: Accepted

#2 [17기 김채현] PostingView 작성 (GET)
  posting/urls.py
  posting/views.py
  sweethome/urls.py
Labels: Status: Accepted

#6 [17기 박재현] order, posting 앱 models.py 수정
  order/migrations/0002_auto_20210222_1154.py
  order/migrations/0003_auto_20210223_0714.py
  order/models.py
  posting/migrations/0005_auto_20210222_1154.py
  posting/models.py
Labels: Status: Accepted

#5 [17기 박재현] 상품 리뷰 조회, 정렬 및 필터링
  product/urls.py
  product/views.py
  sweethome/urls.py
Labels: Status: Accepted

#3 [17기 조수아] ProductView 수정
  product/urls.py
  product/views.py
Labels: Status: Accepted

#4 [17기 김채현] Modify : 리뷰 내용대로 수정
  posting/models.py
  posting/urls.py
  posting/views.py
Labels: Status: 추가 기능 구현중

#7 [17기 이준하]유저 view.py Signin 작성 완료, postingscrapview 작성 완료
  .gitignore
  sweethome/urls.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: Accepted

#8 [17기 박재현] 리뷰 좋아요 뷰 작성
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210222_1154.py
  order/migrations/0003_auto_20210223_0714.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210218_0722.py
  product/migrations/0003_auto_20210218_1045.py
  product/migrations/0004_auto_20210219_0534.py
  product/urls.py
  product/views.py
  user/migrations/0001_initial.py
  user/migrations/0002_auto_20210219_0056.py
Labels: Status: Accepted

#9 [17기 조수아] ProductDetailView 작성
  product/urls.py
  product/views.py
Labels: Status: Accepted

#11 [17기 조수아] CategoryView 작성
  product/urls.py
  product/views.py
Labels: Status: 리뷰 요청

#15 [17기 조수아] ProductView 수정
  product/views.py
Labels: Status: Accepted

#10 [17기 김채현] PostingLikeView 작성
  posting/urls.py
  posting/views.py
  sweethome/urls.py
  user/utils.py
Labels: Status: Accepted, Status: 리뷰 요청

#13 [17기 박재현] 장바구니에 상품 담기 기능 구현
  product/urls.py
  product/views.py
Labels: Status: Accepted

#14 [17기 박재현] 장바구니 조회, 업데이트 기능 추가
  order/views.py
Labels: Status: 리뷰 요청

#16 [17기 이준하] PostingScrapView 작성
  posting/urls.py
  posting/views.py
Labels: Status: 리뷰 요청

#19 [17기 김채현] indent 수정
  posting/views.py
Labels: Status: 리뷰 요청

#17 [17기 박재현] 장바구니 로직 변경
  order/urls.py
  order/views.py
  product/views.py
  sweethome/urls.py
Labels: Status: Accepted

#20 [17기 조수아] ProductView 수정
  product/views.py
Labels: Status: Accepted

#21 [17기 김채현] PostingView 수정
  posting/views.py
Labels: Status: 리뷰 요청

#22 [17기 김채현] PostingView 로직 일부 수정, user default image 변경
  posting/views.py
  user/migrations/0002_auto_20210226_0356.py
  user/models.py
Labels: Status: Accepted
